import java.io.File;

import java.io.FileReader;
import java.util.List;

import io.kubernetes.client.ApiClient;
import io.kubernetes.client.apis.AppsV1beta1Api;
import io.kubernetes.client.models.AppsV1beta1Deployment;
import io.kubernetes.client.models.AppsV1beta1DeploymentSpec;
import io.kubernetes.client.models.V1Container;
import io.kubernetes.client.models.V1EnvVar;
import io.kubernetes.client.models.V1PodSpec;
import io.kubernetes.client.models.V1PodTemplateSpec;
import io.kubernetes.client.util.ClientBuilder;
import io.kubernetes.client.util.KubeConfig;
import io.kubernetes.client.util.Yaml;

public class CreateDeployment {

    public static void main(String[] args) throws Exception {
        // file path to your KubeConfig
        String kubeConfigPath = System.getProperty("user.home") + "/Users/yngliu/.kube/config";
        String namespace = "default";
        String filePath = System.getProperty("user.home") + "/k8s-script/octant_deployment.yaml";
        
        String kubeconfig = "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EY3lOVEEzTVRFd09Gb1hEVEk1TURjeU16QTNNVEV3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkpECnFDb01wUlo0cW5NaUlZNUhjcnNwbWlXWjhoSzlkNDBNcG9CMWxoRXRvTS9tT1ptd1ZGbnFGa013RHFSaGhuRVEKSDlwYkNWZTBWQ0tXNUNtSGtkVnNqOXU4NFh4dUMvSFZXZktYVVF1aDRFSDdod3UwQ0hHTjRjU1RCTkI5YTBzNgpFaDUrdzNmRjdYTlJ0YSs5Z0hUR3hyd1MrWDRTUGtQbWJNdnVydGFZZE84MEJpeDBJZmthRFlyOTRUUVlaQldYClYyYjVXYjVwOXVudFphV0ZKQzl0REtmQjRmQXNlOHZKZWtFM2JLSW5tcWl5dnlIV3lLQk4vdmQ2U3hmSWZ0aVYKZzM5RlQwVFF1ZThVWElpZy9QT0pTY0FhUVlhUmR5ZFNtbUNDYzVMeUp4ZXlPdFcxbnlKQW5qcHRSeUMvbVE3ZwpyaVEyL2pqOGFWc3J6SXFwcFo4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCQ2c3ak1CWnhWdVRNY29tcFZYZHFyUndUc1d3Y1VjMHpkN1JWaGVSK2Fpd1RZY3hkTQpad0Z4TEJRTHQzL1kyZzNac1NLcnUya0IzL21FWTB1Vi90M0hBdFo2TlNDc0QzOHI2RFl6RUVHcEJWNHYza05PCjN4WFJMZGNwQXM1VGIxUFVaMlY5NkRrMStmN21jZ254T0ZXY08vR1RUUlRscFRXckdxL1FZa29IQ0RFSnMwa2oKcGx2U0VMYmRudFhZMXB3WW9BcVlqU0tacWFkTktmU2NPM3FwNnZWeFQzT2VnY01LVFdySVRlVFFoM3Zoa2JRUQpXWTFQd2R2SUtMTkF2RERVOXdROEU3b05mYUxpREMxZk9VUkFubHRVcUNma09Gemx3cnpRL3lFVThyS25KcTNzCitJR3JIRFgvS3dnV1pWWnhmVjYwdnI2UGgwMVA3VC8yQndpRgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg== \n    server: https://10.184.100.10:8443\n  name: minikube\ncontexts:\n- context:\n    cluster: minikube\n    user: minikube\n  name: minikube\ncurrent-context: minikube\nkind: Config\npreferences: {}\nusers:\n- name: minikube\n  user:\n    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBRENDQWVpZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EZ3dOVEE1TXpJd01Wb1hEVEl3TURnd05UQTVNekl3TVZvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDMXR4SHkzNjhvYSsybkdzaWp0d1l5d2Y3bDRMMGEKblo5Nlg0MnpRSXB6TWEvSCtvK2JUN3VBdFdmMjMzaDUzMnFRY0gwNnRXc3h5T1lYSFYzdFY5WjFjbEZCTTFMQgp1bU1qQm4yZVcrL084T1FCbjlxR2Naa2tDUFlyM2xUeDFFSUJGRGZ1Y3dtRDlMSnZtbmRVejEyb1FkMUNFeXRnClZpbXpCU1lPOHR3RjZsZFpHb011bWNJL21WaERMY2VIQThvNzRZUjhPVGFybXdNZGNJeUhlZmpBR2pERFBLYU4KRllnZm4wZGJmQjFTcmhVcUYwVTFrVkFLZFZkdnNqYm9FN2lDVlMwanh2NmFvSTZpM1BqOEdkMzlZSFpkaG9LOQpCSXlac0dPd01MTXJSNldLc3llYXU3T2JzRGZMYlZVU3doSXM4b1J0TXhVZXB4MmIwNk1zcUJ2TkFnTUJBQUdqClB6QTlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBUFpQS0lUSWtSdkgwUG5QcQpoQmwrMmR6YTlUTkN1UUFLNmFuendEVENxU1RjUGgzenY3MTdNdGxmZDFFWUpUcDZ1KzVwUjdIN1NHSG9ha1BICkp5L2JVSG9IWitRYzBWRHBiSnBJRVcyTXpLS0RlaE1SbEcxYnQ4emJUTDcyRzl5bnZ0ODdHU21HYXdpam5SVVIKdXNEcHhSdm92YzNWMkp3SlZ4UUJxZTBEOHpITG9oVDVCb01zQzB0SEgzMzN6akJ2dGpnSXNhSzF1T0pacTRPNApoTGdtWlo3UUdKbTdSeTR5T1BYVVltKzJ0TU4vNGJiWGRRaElCS2VnaWQrTHo2YWZLV0hPYThEdFl6R1FraFhGClVubFVWLyttb2xJSXFWV1JCNENTMGF0cmtSY3FWTkU4K1RDSWFiY01uV3BIeGJiVHdnOVZvVk1za2NTRzdGUWoKR2syaGJ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= \n    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBdGJjUjh0K3ZLR3Z0cHhySW83Y0dNc0grNWVDOUdwMmZlbCtOczBDS2N6R3Z4L3FQCm0wKzdnTFZuOXQ5NGVkOXFrSEI5T3JWck1jam1GeDFkN1ZmV2RYSlJRVE5Td2Jwakl3WjlubHZ2enZEa0FaL2EKaG5HWkpBajJLOTVVOGRSQ0FSUTM3bk1KZy9TeWI1cDNWTTlkcUVIZFFoTXJZRllwc3dVbUR2TGNCZXBYV1JxRApMcG5DUDVsWVF5M0hod1BLTytHRWZEazJxNXNESFhDTWgzbjR3Qm93d3p5bWpSV0lINTlIVzN3ZFVxNFZLaGRGCk5aRlFDblZYYjdJMjZCTzRnbFV0SThiK21xQ09vdHo0L0JuZC9XQjJYWWFDdlFTTW1iQmpzREN6SzBlbGlyTW4KbXJ1em03QTN5MjFWRXNJU0xQS0ViVE1WSHFjZG05T2pMS2dielFJREFRQUJBb0lCQVFDV21CNlc0b3Y5K3R3YwpsZFRiNE8yUkdUY08rZDZlZFN6YXROL3hRemE2V3Q0cjVGb3BRNzNINEE5R0NGT0c1UUlpckNjTWhaZE56Z25wCjlCdUlmRGd1WTB3MXRid0s4MVgvaS95RlJmb0t6WmFZUmd0TFNrKzVEbmc5U09lcTl0YXdvRG51TW9ZYlJxcXUKVlJ3NlBCU0pRZlNGTXUvS3lmMks4R1JuRlJ3RkJaZ25mc044WFU0THJGK2Y3STlnWUl5VlpvV3k1YW9kM0VSSApYYjl2dzZKRER1a0NsL2J0WHBsRWdhdkNVNURTSGhNZDJ3MFNRUFh3Mjl2c085MFhpUEhPT2JLM1JDRkd5N000CnRaRzRTY3F3V2FwVHJ6U2hNM28rR3dudkRkYXdNVUpLRXJ6bmRCTUJoU3Nmc3VkaS9lVWZZQ2tHU2NFKy9QUmsKa0RiU1E1VGRBb0dCQU5DcDNXdzBGZGZ4dUNSUzd3cUhmRVljTFUzUjFWYU9zMDIrbFlqRThLZ215aHY5cS9pdApaOGZ3dlN0bW9SYnRpdnBqb1JlMVo3NUNtWW1EWm9PcDVMRkZ6U3ByYS81UDJjMHVhZlZxOEIxeis0UDVmNmZ6CmxvWlZ6MlZqM2g2VGRoVW9qNGhiSHdCaUNJUVhDWTFmTEdBUCt2WEJNV3hDWDdTRFU2T1owaVkzQW9HQkFON3cKTFFIMStQaWExcVMzRG1mTFFNOXVMcEdaZ1VTdERKT0JueUI4WE5iQThuam43a284TkpSdXc3Yy80ZHZXem5TRwpHQ2pVQk1qMktOUFJyMHNQYjVKK1lCbzFFRm9tS3RoWFlMenNSOUI4ZWxaK0ljUk1GS0N0dzdrTEhRMGtzWTJLCkl4bFczUTlIdk9zemVrTkFDeGphNGk5Tm0yMS9BM2d3dXBSaUtJd2JBb0dCQU1QN1p6Nmp4UWhudmQ1UURyaEMKL0pRVkR2QVNiMSsyOCszSFhVZHlRZDZOWURMZUZWR2gvT0dyMk9FVXFhU1JRNEZkWmdhUW1YbjNyNkdheXdSSwo0OE1rbmtpRFVKRXhpbzNPVkRMdlY4c3lEaitzYlJ2Z0M3YnNqYmpiRGRxR0FkaHBtallsNzM0NmxXa0xBaXZJCkFqUFBqcFNYK2NXR3FjRXZ2N1RmV3FRTkFvR0FmV3kwZGFEMEpMSEFSc1V5VnBUVWJwODNsZlM5OUd4RFlnMlEKQUEvWGozN1lLOHVZbGExUGk1N1JmNXh5TG1Pb25ZZi91YUNtM0lVWkxTcVFLM09RdXVOY29BSHdwRGRLN1pJagpPOGJYRkdXajBsdCtGZGtUMWQ1TStpTlZnZHArQmZxTWlxb0REcUMybWNESmJXSnZtOWt4WFptVTgwSjlLamFJCkVna3pkTGNDZ1lFQXlIdEgrNzdKQXRhTk0rMU5TdnZ2d0NRMHh1Y3ZVZldpR1BJaStGVTBLaEE2cXE5VllBaFgKV2Nwd3hmaDJuazdPbnlNTU9WR051ZmdDN1JnVVVUdUNIUkNaeXZaV2VXU0oyZysrdmdYWmxGRzczbFMvYjgxdwpMZHN0SVBibThvYWxUSHFkZzdJaUNhdU92cWllMHN2eGtLdlVPTHlsQ0p2NXlOYVlYVkN0cjZJPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=\n";

        // loading the out-of-cluster config, a kubeconfig from file-system
        ApiClient client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(kubeConfigPath))).build();

        AppsV1beta1Api api = new AppsV1beta1Api(client);
        
        AppsV1beta1Deployment deployBody = (AppsV1beta1Deployment) Yaml.load(new File(filePath));
        AppsV1beta1DeploymentSpec spec = deployBody.getSpec();
        V1PodTemplateSpec template = spec.getTemplate();
        V1PodSpec podSpec = template.getSpec();
        List<V1Container> containers = podSpec.getContainers();
        for (V1Container container : containers) {
            V1EnvVar envVar = new V1EnvVar();
            envVar.setName("KUBECONFIG");
            envVar.setValue(kubeconfig);
            container.addEnvItem(envVar);
        }
        
        AppsV1beta1Deployment deployment = api.createNamespacedDeployment(namespace, deployBody, null, null, null);        
        System.out.println(deployment.getKind() + " " + deployment.getMetadata().getName() + " deployed.");
    }

}
